# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0004_auto_20170506_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodehomework',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
