# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 11:32
from __future__ import unicode_literals

from django.db import migrations, models
import elearning.models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0006_auto_20170506_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='material_name',
        ),
        migrations.AlterField(
            model_name='material',
            name='material_file',
            field=models.FileField(blank=True, null=True, upload_to=elearning.models.get_file_path),
        ),
    ]
